version: '2'

services:
    backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile            
        entrypoint: /app/docker/backend/wsgi-entrypoint.sh
        volumes:
            - static_volume:/app/backend/django_static
            - request_volume:/app/backend/request_logs/
        expose:
            - 8000    
        depends_on:
            - pgdb    
    nginx: 
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 80:80
        volumes:
            - static_volume:/app/backend/django_static
            - ./docker/nginx/development:/etc/nginx/conf.d
        depends_on: 
            - backend
    pgdb:
        image: 
            postgres
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        container_name: 
            pgdb
        volumes:
        - pgdbdata:/var/lib/postgresql/data/
        expose:
            - 5432    
volumes:
    static_volume: {}
    request_volume: {}
    pgdbdata: {}